"""empty message

Revision ID: 69f1027696dd
Revises: 3d7ca9f45ef8
Create Date: 2023-05-20 08:25:33.746339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f1027696dd'
down_revision = '3d7ca9f45ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('cif',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('cif',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
