"""empty message

Revision ID: 9de7fd6f17e6
Revises: 2194a446d473
Create Date: 2023-04-24 13:35:25.269754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de7fd6f17e6'
down_revision = '2194a446d473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_avatar_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_avatar_key', ['avatar'])

    # ### end Alembic commands ###
