"""empty message

Revision ID: eac2b499b82d
Revises: c5fe480484d9
Create Date: 2023-05-02 10:19:44.985126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac2b499b82d'
down_revision = 'c5fe480484d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
